### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by collegeimprovements** [atweiden/fzf-extras#2]
Would it be like putting fzf-extras.sh adn fzf-extras.zsh in my path location?

**Comment by atweiden** [comment]
Here's an installation script:

``` bash
#!/bin/bash

# get fzf-extras
git clone https://github.com/atweiden/fzf-extras ~/.fzf-extras

# bash setup
cat <<'EOF' >> ~/.bashrc
[[ -e ~/.fzf-extras/fzf-extras.sh ]] && . ~/.fzf-extras/fzf-extras.sh
EOF

# zsh setup
cat <<'EOF' >> ~/.zshrc
[[ -e ~/.fzf-extras/fzf-extras.zsh ]] && . ~/.fzf-extras/fzf-extras.zsh
EOF
```

Source fzf-extras.sh if your $SHELL is bash. Source fzf-extras.zsh if your $SHELL is zsh. [On Arch](https://aur.archlinux.org/packages/fzf-extras/), I'm installing to `/etc/profile.d`.

**Comment by collegeimprovements** [comment]
Unfortunately I'm getting `command not found error`.

**Comment by atweiden** [comment]
What's your OS? Do you have Git installed?

**Comment by collegeimprovements** [comment]
I run the script.
It downloaded .fzf-extras to my home directory. 
And added `[[ -e ~/.fzf-extras/fzf-extras.zsh ]] && . ~/.fzf-extras/fzf-extras.zsh` line to my .zshrc

How can I source it ?

**Comment by atweiden** [comment]
Your shell should already be sourcing ~/.zshrc if I'm not mistaken (not a zsh user myself). This repo contains bindings mainly for Bash. You won't get much out of fzf-extras by using zsh at the moment.

**Comment by collegeimprovements** [comment]
hmmm. Thanks :)
I should learn and appreciate about what I already have :)
