### ISSUE TITLE
Show files from `git status`

### ISSUE THREAD

**Issue by danihodovic** [atweiden/fzf-extras#3]
I think it would be very handy to show files from `git status`. Do you think it could be added to this repo?

**Comment by atweiden** [comment]
That's a good idea, and yes.

**Comment by atweiden** [comment]
I've opened a new [project](https://github.com/atweiden/fzf-extras/projects/1) for this task. Moving feature requests to there seems a better fit than placing feature requests alongside bugs in the issue tracker.
