### ISSUE TITLE
Mutating IFS environment variable globally causes breakage

### ISSUE THREAD

**Issue by linduxed** [atweiden/fzf-extras#9]
Mutating the `IFS` environment variable without restoring it to its original state can break other shell scripts relying on `IFS` being unmodified.

In the `fe` function, prior to 63260197bf9419bf980e65dbff8d096c4c992046 the `IFS` environment variable was set and then `unset`. The behaviour of Zsh (and probably Bash, although I don't know for sure) with an unset `IFS` is to use the default value of `IFS`. This probably also means that before 63260197bf9419bf980e65dbff8d096c4c992046, if one had a custom IFS that differed from the default one, it got clobbered and the default one was used instead (due to the `unset`).

The intent seems to be that `IFS` should temporarily be set to a different value, which is not the case right now.

Relatedly, the `fo` function exhibits the same problematic behaviour.

**Comment by atweiden** [comment]
I'm reading [here](http://unix.stackexchange.com/a/92273) that `local IFS` within a function as per https://github.com/atweiden/fzf-extras/commit/513852486861aed038b492656645ac940fbca616 is a possible solution. Can you pull the [fix-ifs branch](https://github.com/atweiden/fzf-extras/tree/fix-ifs) and see if that fixes #9?

**Comment by linduxed** [comment]
That does seem to fix the problem, yes. I've only tried for Zsh, however.

**Comment by atweiden** [comment]
[fixed](https://github.com/atweiden/fzf-extras/pull/10)
